- name: install deb packages
  apt:
    state: latest
    name: "{{ item }}"
    update_cache: true
  with_items:
    - apt-file
    - byobu
    - devscripts
    - git
    - lnav
    - nmap
    - python3-pip
    - sshuttle
    - unzip

- name: Ensure snapd is installed (optional, but good practice)
  ansible.builtin.package:
    name: snapd
    state: present

- name: Install snap packages
  community.general.snap:
    name: "{{ item }}"
    classic: true
    state: present
  with_items:
    - yq
    - hotsos
    - xsos
    - juju
    - terraform

- name: Install lxd snap package
  community.general.snap:
    name: "{{ item }}"
    classic: true
    state: present
    channel: "{{ lxd_version }}"
  with_items:
    - lxd

- name: Add existing user "{{ ansible_user }}" to groups "lxd"
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: "lxd"
    append: true

- name: get preseed.yaml
  set_fact:
    preseed: "{{ lookup('template', 'preseed.yaml.j2') }}"

- name: lxd init lxd-server.yml
  command: lxd init --preseed <
  args:
    stdin: "{{ preseed }}"
    creates: "{{ lxd_init_file_test }}"


- name: Copy tf dir to the remote home directory
  ansible.builtin.copy:
    src: ../terraform/            # trailing slash = copy contents
    dest: "/home/{{ ansible_user }}/terraform/"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'
  tags:
    - copy_tf_scripts

- name: Grab iptables NAT table
  command: iptables -t nat -L PREROUTING
  register: iptables_nat
  changed_when: False

- name: Add iptables masquerading to enable NATing
  command: |
    iptables -t nat -I PREROUTING -i {{ outbound_interface }} -p TCP -d {{ ansible_default_ipv4.address }} --dport 5240 -j DNAT --to-destination {{ maas_ip }}:5240 \
    -m comment --comment 'maas_container_forward'
  when:
    - '"maas_container_forward" not in iptables_nat.stdout'

# - name: Write file to remote host
#   ansible.builtin.copy:
#     dest: "/home/{{ ansible_user }}/conf.env"
#     content: "{{ lookup('template', 'se-repros.env.j2') }}"

# - name: git checkout
#   git:
#     repo: "https://{{ github_username }}:{{ lookup('env', 'github_token') }}@github.com/canonical/se-support-reproducer-templates.git"
#     dest: "/home/{{ ansible_user }}/se-support-reproducer-templates"
#     version: main